/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/ariannamethod/arianna.c/inner_world */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 19 "blood.go"

#include <stdlib.h>
#include <dlfcn.h>

// Function pointer type for LoRA apply
typedef void (*lora_apply_fn)(float* weights, float* input, float* output, int dim);

#line 1 "cgo-generated-wrapper"

#line 17 "cgo_bridge.go"

#include <stdlib.h>
#include <string.h>

// Snapshot struct for C
typedef struct {
    float arousal;
    float valence;
    float entropy;
    float coherence;
    float trauma_level;
    int loop_count;
    int abstraction_depth;
    int self_ref_count;
    float drift_direction;
    float drift_speed;
    float memory_pressure;
    float focus_strength;
    float wander_pull;
    float prophecy_debt;
    float destiny_pull;
    float wormhole_chance;
} InnerWorldSnapshot;

// Text analysis struct for C
typedef struct {
    float trauma_activation;
    float identity_pull;
    float repetition_score;
    float abstraction_score;
    float self_ref_score;
    float overthink_total;
    float focus_strength;
    float destiny_bias;
    int wormhole_active;
    int wormhole_skip;
    float temporal_dissonance;
} InnerWorldTextAnalysis;

#line 1 "cgo-generated-wrapper"

#line 15 "cloud.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 20 "high.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* blood_compile_lora(char* name, int inDim, int outDim, int rank);
extern char* blood_compile_emotion(char* name, float valence, float arousal);
extern char* blood_compile_raw(char* name, char* code);
extern char* blood_get_temp_dir(void);
extern void inner_world_init(void);
extern void inner_world_shutdown(void);
extern void inner_world_step(float dt);
extern void inner_world_auto_step(void);
extern float inner_world_get_arousal(void);
extern float inner_world_get_trauma(void);
extern float inner_world_get_coherence(void);
extern float inner_world_get_prophecy_debt(void);
extern void inner_world_get_snapshot(InnerWorldSnapshot* out);
extern void inner_world_set_arousal(float v);
extern void inner_world_set_trauma(float v);
extern void inner_world_set_coherence(float v);
extern void inner_world_add_prophecy_debt(float delta);
extern void inner_world_process_text(char* text, InnerWorldTextAnalysis* out);
extern float inner_world_check_trauma(char* text);
extern void inner_world_accumulate_prophecy_debt(float probability);
extern int inner_world_check_wormhole(void);
extern float inner_world_get_destiny_bias(void);
extern int inner_world_get_lookahead(void);
extern void inner_world_set_lookahead(int n);
extern void inner_world_focus(char* target, float strength);
extern int inner_world_is_wandering(void);
extern void inner_world_add_memory(char* content, float emotion, float arousal);
extern void inner_world_nudge_emotion(float d_valence, float d_arousal);
extern void inner_world_get_dominant_emotion(char* buf, int buf_size);
extern int inner_world_is_spiraling(void);
extern void inner_world_suggest_break(char* buf, int buf_size);
extern void inner_world_dsl_destiny(float strength);
extern void inner_world_dsl_prophecy(int lookahead);
extern void inner_world_dsl_wormhole(float chance);
extern void inner_world_dsl_velocity(int mode);
extern void inner_world_dsl_pain(float level);
extern void inner_world_dsl_tension(float level);
extern void inner_world_dsl_dissonance(float level);
extern int inner_world_set_param(char* name, float value);
extern float inner_world_get_param(char* name);
extern int inner_world_load_config(char* path);
extern int inner_world_save_config(char* path);
extern int cloud_init(char* weightsDir);
extern int cloud_preprocess(char* text);
extern float cloud_get_temperature_bias(void);
extern char* cloud_get_primary(void);
extern char* cloud_get_secondary(void);
extern float cloud_get_chamber(char* name);
extern char* cloud_ping(char* text);
extern void cloud_stop(void);
extern void cloud_free(void);
extern float high_entropy(char* text);
extern float high_emotional_score(char* text);
extern float high_perplexity(char* text);
extern float high_semantic_distance(char* text1, char* text2);
extern float high_emotional_alignment(char* text1, char* text2);
extern float high_ngram_overlap(char* text1, char* text2, int n);
extern float high_analyze_valence(char* text);
extern float high_analyze_arousal(char* text);
extern float high_predictive_surprise(char* expected, char* actual);
extern float high_resonance_coupling(float valence, float arousal, float entropy, char* text, float schumann);
extern float high_text_rhythm_avg(char* text);
extern float high_text_rhythm_variance(char* text);

#ifdef __cplusplus
}
#endif
